# -*- mode: Python; indent-tabs-mode: t -*-
# Copyright (C) 2012, 2018  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import os.path

Import("env","libcore")
local_env=env.Clone()
local_env.MergeFlags(["!pkg-config --cflags --libs giomm-2.4"])
local_env.Prepend(LIBS=local_env["libcore"])

service=local_env.Program("RHVoice-service",["service.cpp","common.cpp"])
client=local_env.Program("RHVoice-client",["client.cpp","common.cpp"])
local_env.Depends(service,libcore)
local_env.Depends(client,libcore)
if local_env["PLATFORM"]!="win32":
    local_env.InstallProgram(service)
    local_env.InstallProgram(client)
    local_env.InstallServiceFile("com.github.OlgaYakovleva.RHVoice.service.in")
