/*******************************************************/
/**  Autogenerated cart trees for ru_phrasing    */
/*******************************************************/

#include "cst_string.h"
#include "cst_cart.h"
#include "cst_regex.h"
#include "ru_phrasing_cart.h"

static const cst_cart_node ru_phrasing_cart_nodes[] = {
{ 0, CST_CART_OP_IS, CTNODE_ru_phrasing_NO_0000, (cst_val *)&val_0000},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 1, CST_CART_OP_IS, CTNODE_ru_phrasing_NO_0002, (cst_val *)&val_0000},
{ 2, CST_CART_OP_IS, CTNODE_ru_phrasing_NO_0003, (cst_val *)&val_0002},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0003 },
{ 3, CST_CART_OP_IS, CTNODE_ru_phrasing_NO_0005, (cst_val *)&val_0002},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 4, CST_CART_OP_IS, CTNODE_ru_phrasing_NO_0007, (cst_val *)&val_0004},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0003 },
{ 4, CST_CART_OP_IS, CTNODE_ru_phrasing_NO_0009, (cst_val *)&val_0005},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0003 },
{ 4, CST_CART_OP_IS, CTNODE_ru_phrasing_NO_0011, (cst_val *)&val_0006},
{ 5, CST_CART_OP_IS, CTNODE_ru_phrasing_NO_0012, (cst_val *)&val_0004},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0003 },
{ 5, CST_CART_OP_IS, CTNODE_ru_phrasing_NO_0014, (cst_val *)&val_0005},
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0001 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0007 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0007 },
{ 255, CST_CART_OP_NONE, 0, (cst_val *)&val_0007 },
{ 255, CST_CART_OP_NONE, 0, 0}};


static const char * const ru_phrasing_feat_table[] = {
"n.name",
"R:Token.n.name",
"R:Token.parent.lisp_ru_token_punc_minor_break",
"R:Token.parent.lisp_ru_token_punc_major_break",
"R:Token.parent.n.name",
"R:Token.parent.n.prepunctuation",
NULL };

const cst_cart ru_phrasing_cart = {
  ru_phrasing_cart_nodes,
  ru_phrasing_feat_table
};
