/*******************************************************/
/**  Autogenerated cart tree for ru_phrasing    */
/**  from src/lib    */
/*******************************************************/

DEF_STATIC_CONST_VAL_STRING(val_0000,"0");
DEF_STATIC_CONST_VAL_STRING(val_0001,"BB");
#define CTNODE_ru_phrasing_NO_0000 2
DEF_STATIC_CONST_VAL_STRING(val_0002,"1");
DEF_STATIC_CONST_VAL_STRING(val_0003,"B");
#define CTNODE_ru_phrasing_NO_0003 5
#define CTNODE_ru_phrasing_NO_0005 7
DEF_STATIC_CONST_VAL_STRING(val_0004,"-");
#define CTNODE_ru_phrasing_NO_0007 9
DEF_STATIC_CONST_VAL_STRING(val_0005,"--");
#define CTNODE_ru_phrasing_NO_0009 11
DEF_STATIC_CONST_VAL_STRING(val_0006,"");
#define CTNODE_ru_phrasing_NO_0012 14
#define CTNODE_ru_phrasing_NO_0014 16
DEF_STATIC_CONST_VAL_STRING(val_0007,"NB");
#define CTNODE_ru_phrasing_NO_0011 17
#define CTNODE_ru_phrasing_NO_0002 18
