/*******************************************************/
/**  Autogenerated phoneset trees for ru    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset ru_phoneset;


static const char * const ru_featnames[] = {
 "vc",
 "vlng",
 "vheight",
 "vfront",
 "vrnd",
 "ctype",
 "cplace",
 "cvox",
 "csoft",
 NULL };

static const char * const ru_phonenames[] = {
 "pau",
 "ii",
 "yy",
 "uu",
 "ee",
 "oo",
 "aa",
 "a",
 "e",
 "i",
 "y",
 "u",
 "ae",
 "ay",
 "ur",
 "p",
 "pp",
 "b",
 "bb",
 "t",
 "tt",
 "d",
 "dd",
 "k",
 "kk",
 "g",
 "gg",
 "c",
 "ch",
 "f",
 "ff",
 "v",
 "vv",
 "s",
 "ss",
 "z",
 "zz",
 "sh",
 "sch",
 "zh",
 "h",
 "hh",
 "m",
 "mm",
 "n",
 "nn",
 "l",
 "ll",
 "r",
 "rr",
 "j",
 NULL };

static const int ru_fv_000[] = { 0, 1, 1, 1, 1, 1, 1, 1, 1,   -1 };
static const int ru_fv_001[] = { 2, 3, 4, 5, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_002[] = { 2, 3, 4, 6, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_003[] = { 2, 3, 4, 4, 2, 1, 1, 1, 1,   -1 };
static const int ru_fv_004[] = { 2, 3, 6, 5, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_005[] = { 2, 3, 6, 4, 2, 1, 1, 1, 1,   -1 };
static const int ru_fv_006[] = { 2, 3, 5, 6, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_007[] = { 2, 7, 8, 9, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_008[] = { 2, 7, 6, 8, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_009[] = { 2, 7, 9, 8, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_010[] = { 2, 7, 9, 6, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_011[] = { 2, 7, 4, 4, 2, 1, 1, 1, 1,   -1 };
static const int ru_fv_012[] = { 2, 10, 6, 6, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_013[] = { 2, 10, 6, 6, 0, 1, 1, 1, 1,   -1 };
static const int ru_fv_014[] = { 2, 10, 9, 9, 2, 1, 1, 1, 1,   -1 };
static const int ru_fv_015[] = { 0, 1, 1, 1, 1, 7, 3, 0, 0,   -1 };
static const int ru_fv_016[] = { 0, 1, 1, 1, 1, 7, 3, 0, 2,   -1 };
static const int ru_fv_017[] = { 0, 1, 1, 1, 1, 7, 3, 2, 0,   -1 };
static const int ru_fv_018[] = { 0, 1, 1, 1, 1, 7, 3, 2, 2,   -1 };
static const int ru_fv_019[] = { 0, 1, 1, 1, 1, 7, 11, 0, 0,   -1 };
static const int ru_fv_020[] = { 0, 1, 1, 1, 1, 7, 11, 0, 2,   -1 };
static const int ru_fv_021[] = { 0, 1, 1, 1, 1, 7, 11, 2, 0,   -1 };
static const int ru_fv_022[] = { 0, 1, 1, 1, 1, 7, 11, 2, 2,   -1 };
static const int ru_fv_023[] = { 0, 1, 1, 1, 1, 7, 12, 0, 0,   -1 };
static const int ru_fv_024[] = { 0, 1, 1, 1, 1, 7, 12, 0, 2,   -1 };
static const int ru_fv_025[] = { 0, 1, 1, 1, 1, 7, 12, 2, 0,   -1 };
static const int ru_fv_026[] = { 0, 1, 1, 1, 1, 7, 12, 2, 2,   -1 };
static const int ru_fv_027[] = { 0, 1, 1, 1, 1, 10, 11, 0, 0,   -1 };
static const int ru_fv_028[] = { 0, 1, 1, 1, 1, 10, 10, 0, 2,   -1 };
static const int ru_fv_029[] = { 0, 1, 1, 1, 1, 13, 14, 0, 0,   -1 };
static const int ru_fv_030[] = { 0, 1, 1, 1, 1, 13, 14, 0, 2,   -1 };
static const int ru_fv_031[] = { 0, 1, 1, 1, 1, 13, 14, 2, 0,   -1 };
static const int ru_fv_032[] = { 0, 1, 1, 1, 1, 13, 14, 2, 2,   -1 };
static const int ru_fv_033[] = { 0, 1, 1, 1, 1, 13, 11, 0, 0,   -1 };
static const int ru_fv_034[] = { 0, 1, 1, 1, 1, 13, 11, 0, 2,   -1 };
static const int ru_fv_035[] = { 0, 1, 1, 1, 1, 13, 11, 2, 0,   -1 };
static const int ru_fv_036[] = { 0, 1, 1, 1, 1, 13, 11, 2, 2,   -1 };
static const int ru_fv_037[] = { 0, 1, 1, 1, 1, 13, 10, 0, 0,   -1 };
static const int ru_fv_038[] = { 0, 1, 1, 1, 1, 13, 12, 0, 2,   -1 };
static const int ru_fv_039[] = { 0, 1, 1, 1, 1, 13, 10, 2, 0,   -1 };
static const int ru_fv_040[] = { 0, 1, 1, 1, 1, 13, 15, 0, 0,   -1 };
static const int ru_fv_041[] = { 0, 1, 1, 1, 1, 13, 15, 0, 2,   -1 };
static const int ru_fv_042[] = { 0, 1, 1, 1, 1, 16, 3, 2, 0,   -1 };
static const int ru_fv_043[] = { 0, 1, 1, 1, 1, 16, 3, 2, 2,   -1 };
static const int ru_fv_044[] = { 0, 1, 1, 1, 1, 16, 11, 2, 0,   -1 };
static const int ru_fv_045[] = { 0, 1, 1, 1, 1, 16, 11, 2, 2,   -1 };
static const int ru_fv_046[] = { 0, 1, 1, 1, 1, 3, 11, 2, 0,   -1 };
static const int ru_fv_047[] = { 0, 1, 1, 1, 1, 3, 11, 2, 2,   -1 };
static const int ru_fv_048[] = { 0, 1, 1, 1, 1, 3, 10, 2, 0,   -1 };
static const int ru_fv_049[] = { 0, 1, 1, 1, 1, 3, 10, 2, 2,   -1 };
static const int ru_fv_050[] = { 0, 1, 1, 1, 1, 13, 12, 2, 2,   -1 };
static const int ru_fv_051[] = { 0 };

static const int * const ru_fvtable[] = {
  ru_fv_000, 
  ru_fv_001, 
  ru_fv_002, 
  ru_fv_003, 
  ru_fv_004, 
  ru_fv_005, 
  ru_fv_006, 
  ru_fv_007, 
  ru_fv_008, 
  ru_fv_009, 
  ru_fv_010, 
  ru_fv_011, 
  ru_fv_012, 
  ru_fv_013, 
  ru_fv_014, 
  ru_fv_015, 
  ru_fv_016, 
  ru_fv_017, 
  ru_fv_018, 
  ru_fv_019, 
  ru_fv_020, 
  ru_fv_021, 
  ru_fv_022, 
  ru_fv_023, 
  ru_fv_024, 
  ru_fv_025, 
  ru_fv_026, 
  ru_fv_027, 
  ru_fv_028, 
  ru_fv_029, 
  ru_fv_030, 
  ru_fv_031, 
  ru_fv_032, 
  ru_fv_033, 
  ru_fv_034, 
  ru_fv_035, 
  ru_fv_036, 
  ru_fv_037, 
  ru_fv_038, 
  ru_fv_039, 
  ru_fv_040, 
  ru_fv_041, 
  ru_fv_042, 
  ru_fv_043, 
  ru_fv_044, 
  ru_fv_045, 
  ru_fv_046, 
  ru_fv_047, 
  ru_fv_048, 
  ru_fv_049, 
  ru_fv_050, 
 ru_fv_051 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"-");
DEF_STATIC_CONST_VAL_STRING(featval_1,"0");
DEF_STATIC_CONST_VAL_STRING(featval_2,"+");
DEF_STATIC_CONST_VAL_STRING(featval_3,"l");
DEF_STATIC_CONST_VAL_STRING(featval_4,"5");
DEF_STATIC_CONST_VAL_STRING(featval_5,"1");
DEF_STATIC_CONST_VAL_STRING(featval_6,"3");
DEF_STATIC_CONST_VAL_STRING(featval_7,"s");
DEF_STATIC_CONST_VAL_STRING(featval_8,"2");
DEF_STATIC_CONST_VAL_STRING(featval_9,"4");
DEF_STATIC_CONST_VAL_STRING(featval_10,"a");
DEF_STATIC_CONST_VAL_STRING(featval_11,"d");
DEF_STATIC_CONST_VAL_STRING(featval_12,"p");
DEF_STATIC_CONST_VAL_STRING(featval_13,"f");
DEF_STATIC_CONST_VAL_STRING(featval_14,"b");
DEF_STATIC_CONST_VAL_STRING(featval_15,"v");
DEF_STATIC_CONST_VAL_STRING(featval_16,"n");

static const cst_val * const ru_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 (cst_val *)&featval_2,
 (cst_val *)&featval_3,
 (cst_val *)&featval_4,
 (cst_val *)&featval_5,
 (cst_val *)&featval_6,
 (cst_val *)&featval_7,
 (cst_val *)&featval_8,
 (cst_val *)&featval_9,
 (cst_val *)&featval_10,
 (cst_val *)&featval_11,
 (cst_val *)&featval_12,
 (cst_val *)&featval_13,
 (cst_val *)&featval_14,
 (cst_val *)&featval_15,
 (cst_val *)&featval_16,
 NULL };

const cst_phoneset ru_phoneset = {
  "ru",
  ru_featnames,
  ru_featvals,
  ru_phonenames,
  "pau",
  51,
  ru_fvtable
};
