/*******************************************************/
/**  Autogenerated cart tree for ru_vpair    */
/**  from src/lib    */
/*******************************************************/

DEF_STATIC_CONST_VAL_STRING(val_0000,"+");
DEF_STATIC_CONST_VAL_STRING(val_0001,"0");
DEF_STATIC_CONST_VAL_STRING(val_0002,"proc");
DEF_STATIC_CONST_VAL_STRING(val_0003,"-");
DEF_STATIC_CONST_VAL_STRING(val_0004,"Y");
#define CTNODE_ru_vpair_NO_0003 5
DEF_STATIC_CONST_VAL_STRING(val_0005,"N");
#define CTNODE_ru_vpair_NO_0002 6
DEF_STATIC_CONST_VAL_STRING(val_0006,"v");
#define CTNODE_ru_vpair_NO_0009 11
DEF_STATIC_CONST_VAL_STRING(val_0007,"vv");
#define CTNODE_ru_vpair_NO_0011 13
DEF_STATIC_CONST_VAL_STRING(val_0008,"1");
#define CTNODE_ru_vpair_NO_0013 15
#define CTNODE_ru_vpair_NO_0008 16
#define CTNODE_ru_vpair_NO_0007 17
#define CTNODE_ru_vpair_NO_0019 21
#define CTNODE_ru_vpair_NO_0021 23
#define CTNODE_ru_vpair_NO_0023 25
#define CTNODE_ru_vpair_NO_0018 26
#define CTNODE_ru_vpair_NO_0017 27
#define CTNODE_ru_vpair_NO_0027 29
#define CTNODE_ru_vpair_NO_0006 30
#define CTNODE_ru_vpair_NO_0001 31
#define CTNODE_ru_vpair_NO_0031 33
#define CTNODE_ru_vpair_NO_0000 34
#define CTNODE_ru_vpair_NO_0037 39
#define CTNODE_ru_vpair_NO_0039 41
#define CTNODE_ru_vpair_NO_0041 43
#define CTNODE_ru_vpair_NO_0036 44
#define CTNODE_ru_vpair_NO_0035 45
#define CTNODE_ru_vpair_NO_0048 50
#define CTNODE_ru_vpair_NO_0050 52
#define CTNODE_ru_vpair_NO_0052 54
#define CTNODE_ru_vpair_NO_0047 55
#define CTNODE_ru_vpair_NO_0046 56
#define CTNODE_ru_vpair_NO_0058 60
#define CTNODE_ru_vpair_NO_0060 62
#define CTNODE_ru_vpair_NO_0062 64
#define CTNODE_ru_vpair_NO_0057 65
#define CTNODE_ru_vpair_NO_0056 66
#define CTNODE_ru_vpair_NO_0066 68
#define CTNODE_ru_vpair_NO_0045 69
#define CTNODE_ru_vpair_NO_0034 70
#define CTNODE_ru_vpair_NO_0071 73
#define CTNODE_ru_vpair_NO_0073 75
#define CTNODE_ru_vpair_NO_0075 77
#define CTNODE_ru_vpair_NO_0070 78
