/*******************************************************/
/**  Autogenerated cart tree for ru_vowel_reduction    */
/**  from src/lib    */
/*******************************************************/

DEF_STATIC_CONST_VAL_STRING(val_0000,"1");
DEF_STATIC_CONST_VAL_STRING(val_0001,"a");
DEF_STATIC_CONST_VAL_STRING(val_0002,"aa");
#define CTNODE_ru_vowel_reduction_NO_0001 3
DEF_STATIC_CONST_VAL_STRING(val_0003,"o");
DEF_STATIC_CONST_VAL_STRING(val_0004,"oo");
#define CTNODE_ru_vowel_reduction_NO_0003 5
DEF_STATIC_CONST_VAL_STRING(val_0005,"u");
DEF_STATIC_CONST_VAL_STRING(val_0006,"uu");
#define CTNODE_ru_vowel_reduction_NO_0005 7
DEF_STATIC_CONST_VAL_STRING(val_0007,"e");
DEF_STATIC_CONST_VAL_STRING(val_0008,"ee");
#define CTNODE_ru_vowel_reduction_NO_0007 9
DEF_STATIC_CONST_VAL_STRING(val_0009,"y");
DEF_STATIC_CONST_VAL_STRING(val_0010,"yy");
#define CTNODE_ru_vowel_reduction_NO_0009 11
DEF_STATIC_CONST_VAL_STRING(val_0011,"i");
DEF_STATIC_CONST_VAL_STRING(val_0012,"-");
#define CTNODE_ru_vowel_reduction_NO_0012 14
DEF_STATIC_CONST_VAL_STRING(val_0013,"ii");
#define CTNODE_ru_vowel_reduction_NO_0011 15
DEF_STATIC_CONST_VAL_STRING(val_0014,"N");
#define CTNODE_ru_vowel_reduction_NO_0000 16
DEF_STATIC_CONST_VAL_STRING(val_0015,"pau");
DEF_STATIC_CONST_VAL_STRING(val_0016,"a");
#define CTNODE_ru_vowel_reduction_NO_0017 19
#define CTNODE_ru_vowel_reduction_NO_0016 20
#define CTNODE_ru_vowel_reduction_NO_0021 23
#define CTNODE_ru_vowel_reduction_NO_0020 24
DEF_STATIC_CONST_VAL_STRING(val_0017,"+");
#define CTNODE_ru_vowel_reduction_NO_0025 27
#define CTNODE_ru_vowel_reduction_NO_0024 28
DEF_STATIC_CONST_VAL_STRING(val_0018,"0");
#define CTNODE_ru_vowel_reduction_NO_0029 31
DEF_STATIC_CONST_VAL_STRING(val_0019,"y");
#define CTNODE_ru_vowel_reduction_NO_0032 34
#define CTNODE_ru_vowel_reduction_NO_0031 35
#define CTNODE_ru_vowel_reduction_NO_0028 36
DEF_STATIC_CONST_VAL_STRING(val_0020,"i");
#define CTNODE_ru_vowel_reduction_NO_0038 40
#define CTNODE_ru_vowel_reduction_NO_0040 42
#define CTNODE_ru_vowel_reduction_NO_0042 44
#define CTNODE_ru_vowel_reduction_NO_0037 45
#define CTNODE_ru_vowel_reduction_NO_0045 47
#define CTNODE_ru_vowel_reduction_NO_0047 49
#define CTNODE_ru_vowel_reduction_NO_0036 50
DEF_STATIC_CONST_VAL_STRING(val_0021,"proc");
#define CTNODE_ru_vowel_reduction_NO_0053 55
#define CTNODE_ru_vowel_reduction_NO_0052 56
#define CTNODE_ru_vowel_reduction_NO_0056 58
#define CTNODE_ru_vowel_reduction_NO_0051 59
DEF_STATIC_CONST_VAL_STRING(val_0022,"ur");
#define CTNODE_ru_vowel_reduction_NO_0059 61
DEF_STATIC_CONST_VAL_STRING(val_0023,"ae");
#define CTNODE_ru_vowel_reduction_NO_0061 63
DEF_STATIC_CONST_VAL_STRING(val_0024,"ay");
#define CTNODE_ru_vowel_reduction_NO_0050 64
#define CTNODE_ru_vowel_reduction_NO_0066 68
#define CTNODE_ru_vowel_reduction_NO_0065 69
#define CTNODE_ru_vowel_reduction_NO_0069 71
#define CTNODE_ru_vowel_reduction_NO_0064 72
#define CTNODE_ru_vowel_reduction_NO_0072 74
#define CTNODE_ru_vowel_reduction_NO_0074 76
