/*******************************************************/
/**  Autogenerated cart tree for ru_vowel_reduction    */
/**  from .    */
/*******************************************************/

DEF_STATIC_CONST_VAL_STRING(val_0000,"1");
DEF_STATIC_CONST_VAL_STRING(val_0001,"a");
DEF_STATIC_CONST_VAL_STRING(val_0002,"aa");
#define CTNODE_ru_vowel_reduction_NO_0001 3
DEF_STATIC_CONST_VAL_STRING(val_0003,"o");
DEF_STATIC_CONST_VAL_STRING(val_0004,"oo");
#define CTNODE_ru_vowel_reduction_NO_0003 5
DEF_STATIC_CONST_VAL_STRING(val_0005,"u");
DEF_STATIC_CONST_VAL_STRING(val_0006,"uu");
#define CTNODE_ru_vowel_reduction_NO_0005 7
DEF_STATIC_CONST_VAL_STRING(val_0007,"e");
DEF_STATIC_CONST_VAL_STRING(val_0008,"ee");
#define CTNODE_ru_vowel_reduction_NO_0007 9
DEF_STATIC_CONST_VAL_STRING(val_0009,"y");
DEF_STATIC_CONST_VAL_STRING(val_0010,"yy");
#define CTNODE_ru_vowel_reduction_NO_0009 11
DEF_STATIC_CONST_VAL_STRING(val_0011,"i");
DEF_STATIC_CONST_VAL_STRING(val_0012,"-");
DEF_STATIC_CONST_VAL_STRING(val_0013,"и");
DEF_STATIC_CONST_VAL_STRING(val_0014,"content");
DEF_STATIC_CONST_VAL_STRING(val_0015,"ii");
#define CTNODE_ru_vowel_reduction_NO_0014 16
#define CTNODE_ru_vowel_reduction_NO_0013 17
#define CTNODE_ru_vowel_reduction_NO_0012 18
#define CTNODE_ru_vowel_reduction_NO_0011 19
DEF_STATIC_CONST_VAL_STRING(val_0016,"N");
#define CTNODE_ru_vowel_reduction_NO_0000 20
DEF_STATIC_CONST_VAL_STRING(val_0017,"pau");
DEF_STATIC_CONST_VAL_STRING(val_0018,"a");
#define CTNODE_ru_vowel_reduction_NO_0021 23
#define CTNODE_ru_vowel_reduction_NO_0020 24
#define CTNODE_ru_vowel_reduction_NO_0025 27
#define CTNODE_ru_vowel_reduction_NO_0024 28
DEF_STATIC_CONST_VAL_STRING(val_0019,"+");
#define CTNODE_ru_vowel_reduction_NO_0029 31
#define CTNODE_ru_vowel_reduction_NO_0028 32
DEF_STATIC_CONST_VAL_STRING(val_0020,"0");
#define CTNODE_ru_vowel_reduction_NO_0033 35
DEF_STATIC_CONST_VAL_STRING(val_0021,"y");
#define CTNODE_ru_vowel_reduction_NO_0036 38
#define CTNODE_ru_vowel_reduction_NO_0035 39
#define CTNODE_ru_vowel_reduction_NO_0032 40
DEF_STATIC_CONST_VAL_STRING(val_0022,"i");
#define CTNODE_ru_vowel_reduction_NO_0042 44
#define CTNODE_ru_vowel_reduction_NO_0044 46
#define CTNODE_ru_vowel_reduction_NO_0046 48
#define CTNODE_ru_vowel_reduction_NO_0041 49
#define CTNODE_ru_vowel_reduction_NO_0049 51
#define CTNODE_ru_vowel_reduction_NO_0051 53
#define CTNODE_ru_vowel_reduction_NO_0040 54
DEF_STATIC_CONST_VAL_STRING(val_0023,"proc");
#define CTNODE_ru_vowel_reduction_NO_0057 59
#define CTNODE_ru_vowel_reduction_NO_0056 60
#define CTNODE_ru_vowel_reduction_NO_0060 62
#define CTNODE_ru_vowel_reduction_NO_0055 63
DEF_STATIC_CONST_VAL_STRING(val_0024,"ur");
#define CTNODE_ru_vowel_reduction_NO_0063 65
DEF_STATIC_CONST_VAL_STRING(val_0025,"ae");
#define CTNODE_ru_vowel_reduction_NO_0065 67
DEF_STATIC_CONST_VAL_STRING(val_0026,"ay");
#define CTNODE_ru_vowel_reduction_NO_0054 68
#define CTNODE_ru_vowel_reduction_NO_0070 72
#define CTNODE_ru_vowel_reduction_NO_0069 73
#define CTNODE_ru_vowel_reduction_NO_0073 75
#define CTNODE_ru_vowel_reduction_NO_0068 76
#define CTNODE_ru_vowel_reduction_NO_0076 78
#define CTNODE_ru_vowel_reduction_NO_0078 80
