# Copyright (C) 2010, 2011  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import os.path
Import(["env"])
local_env=env.Clone()
local_env.Prepend(LIBS="RHVoice_core")
local_env.Prepend(LIBPATH=os.path.join("..","core"))
lib_name="RHVoice"
lib_version="1.0.0"
if hasattr(os,"uname") and os.uname()[0]=="Linux" and local_env["enable_shared"]=="yes":
    local_env.Append(SHLINKFLAGS=("-Wl,-soname,${TARGET.file}."+lib_version.split(".")[0]))
src=["lib.cpp"]
if env["PLATFORM"]=="win32":
    dll=local_env.SharedLibrary(lib_name,src+["lib.def"])
    local_env.Install(os.path.join("..","install"),dll)
elif env["enable_shared"]=="yes":
    lib=local_env.SharedLibrary(lib_name,src)
    env.InstallSharedLibrary(lib,lib_version)
else:
        lib=local_env.StaticLibrary(lib_name,src)
        env.InstallStaticLibrary(lib)
