# Copyright (C) 2010, 2011  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os.path
Import(["env","lib_objects"])
local_env=env.Clone()
local_env.Append(CPPPATH="include")
local_env.Append(CPPDEFINES=("AUDIO_PLAY_NONE","1"))
# hts_engine API calls AC_C_BIGENDIAN during configuration
# I do not think my project will be used on such platforms, 
# but as I have included the sources, I should try to configure them properly
if sys.byteorder=="big":
    local_env.Append(CPPDEFINES=("WORDS_BIGENDIAN","1"))
src=Glob(os.path.join("lib","*.c"))
if env["PLATFORM"]=="win32":
    objects=local_env.SharedObject(src)
else:
    objects=local_env.StaticObject(src)
lib_objects.extend(objects)
if local_env["PLATFORM"]=="win32":
    local_env.ConvertNewlines("COPYING")
