import sys
import os.path
Import(["env"])
local_env=env.Clone()
local_env.Append(CPPPATH="include")
local_env.Append(CPPDEFINES=("AUDIO_PLAY_NONE","1"))
# hts_engine API calls AC_C_BIGENDIAN during configuration
# I do not think my project will be used on such platforms, 
# but as I have included the sources, I should try to configure them properly
if sys.byteorder=="big":
    local_env.Append(CPPDEFINES=("WORDS_BIGENDIAN","1"))
src=Glob(os.path.join("lib","*.c"))
env["hts_engine_obj"]=local_env.StaticObject(src)
if local_env["PLATFORM"]=="win32":
    local_env.ConvertNewlines("COPYING")
