version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    target-branch: master
  - package-ecosystem: gradle
    directory: "/src/android"
    schedule:
      interval: daily
    target-branch: master
