#!/usr/bin/python2 -B
# -*- coding: utf-8; mode: Python; indent-tabs-mode: t; tab-width: 4; python-indent: 4 -*-

# Copyright (C) 2012  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import codecs
import rules

if __name__=="__main__":
	r=rules.rules(sys.argv[2])
	with codecs.open(sys.argv[1],"r","utf-8") as f_in:
		with codecs.open(sys.argv[3],"w","utf-8") as f_out:
			for line in f_in:
				entry=line.strip()
				if not entry:
					continue
				if u"ё" in entry:
					f_out.write(entry)
					f_out.write("\n")
				elif sum(1 for c in entry if c.isupper())==1:
					n=next(i for i in xrange(len(entry)) if entry[i].isupper())+1
					word="#"+entry.lower()+"#"
					m=r.match(word)
					if (len(m)!=1) or (m[0][0]+m[0][2]!=n):
						f_out.write(entry)
						f_out.write("\n")
				else:
					f_out.write(entry)
					f_out.write("\n")
