#!/usr/bin/python2
# -*- coding: utf-8; mode: Python; indent-tabs-mode: t; tab-width: 4; python-indent: 4 -*-

# Copyright (C) 2012  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import codecs
import os.path
import collections
import re

vowels=set(u"аеёиоуыэюя")

if __name__=="__main__":
	words=set()
	with codecs.open(sys.argv[1],"r","utf-8") as f:
		words.update(f.read().split())
	lex1=collections.defaultdict(list)
	with codecs.open(sys.argv[2],"r","koi8-r") as f:
		for line in f:
			entry=re.sub(u"^(тр|четыр)е'?х",ur"\1ёх",re.sub(u"(?<=ё)'","",line.strip().lower().replace("`","")))
			if "-" in entry:
				continue
			word=entry.replace("'","")
			if (word not in words) and (word.replace(u"ё",u"е") not in words):
				continue
			pron=re.sub(r"(?u)\w'",lambda m: m.group(0)[0].upper(),entry)
			if u"ё" in word:
				lex1[word.replace(u"ё",u"е")].append(pron)
			elif "'" in entry:
				lex1[word].append(pron)
	for word,variants in lex1.iteritems():
		if len(variants)>1:
			variants[:]=[]
	lex2=collections.defaultdict(list)
	with codecs.open(sys.argv[3],"r","utf-8") as f:
		f.readline()
		for line in f:
			tokens=re.sub(r'[\(\)\"]'," ",line).lower().split()
			if tokens:
				word=tokens[0]
				if (u"ё" in word) or ("-" in word):
					continue
				index=int(tokens[2])-1
				if index<0:
					continue
				vowel_positions=[i for i in xrange(len(word)) if word[i] in vowels]
				if index>=len(vowel_positions):
					continue
				stress_pos=vowel_positions[index]
				pron=list(word)
				if tokens[-1]=="fix_yo":
					pron[stress_pos]=u"ё"
				else:
					pron[stress_pos]=word[stress_pos].upper()
				lex2[word].append(u"".join(pron))
	lex1.update(lex2)
	with codecs.open(sys.argv[4],"w","utf-8") as f:
		for word,variants in sorted(lex1.iteritems(),key=lambda p: p[0]):
			if len(variants)>0:
				pron=variants[0]
				if (u"ё" in pron) or (sum(1 for c in word if c in vowels)>1):
					f.write(pron)
					f.write("\n")
