/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_olga_yakovleva_rhvoice_TTSEngine */

#ifndef _Included_com_github_olga_yakovleva_rhvoice_TTSEngine
#define _Included_com_github_olga_yakovleva_rhvoice_TTSEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    onClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_onClassInit
  (JNIEnv *, jclass);

/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    onInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_onInit
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    onShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_onShutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    doGetVoices
 * Signature: ()[Lcom/github/olga_yakovleva/rhvoice/VoiceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_doGetVoices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_olga_yakovleva_rhvoice_VoiceInfo */

#ifndef _Included_com_github_olga_yakovleva_rhvoice_VoiceInfo
#define _Included_com_github_olga_yakovleva_rhvoice_VoiceInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
