# Copyright (C) 2013  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os.path
Import(["env","libRHVoice_core"])
local_env=env.Clone()
local_env.Prepend(LIBS=libRHVoice_core)
jclasses=local_env.Java(".",os.path.join("android","library","src","com","github","olga_yakovleva","rhvoice"))
local_env.JavaH(Dir(".").srcnode().Dir("android").Dir("library").Dir("jni").File("native.h"),jclasses)
local_env.SharedLibrary("RHVoice_jni",Glob(os.path.join("android","library","jni","*.cpp")))
local_env.Jar("RHVoice",jclasses)
