#!/usr/bin/python2
# -*- coding: utf-8; mode: Python; indent-tabs-mode: t -*-

import sys
import csv
import codecs

if __name__!="__main__":
	sys.exit()

with open("russian-loanwords.csv","r") as ifp:
	with codecs.open("russian-loanwords.txt","w","utf-8") as ofp:
		reader=csv.reader(ifp)
		for row in reader:
			word=row[0].decode("utf-8")
			if word.startswith("#"):
				continue
			trans=row[1].decode("utf-8")
			ofp.write(u" ".join(word)+"\n")
			ofp.write(u" ".join(trans)+"\n")
