#!/usr/bin/python2
# -*- coding: utf-8; mode: Python; indent-tabs-mode: t; tab-width: 4; python-indent: 4 -*-

# Copyright (C) 2012  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import codecs

vowels=set(u"аеёиоуыэюя")

if __name__=="__main__":
	lex=dict()
	with codecs.open(sys.argv[1],"r","utf-8") as f_in:
		f_in.readline()
		for line in f_in:
			tokens=line.strip().lower().replace("("," ").replace(")"," ").replace('"'," ").split()
			word=tokens[0]
			if "-" in word:
				continue
			stress_position=int(tokens[2])
			if stress_position==0:
				continue
			vowel_positions=[i for i in xrange(len(word)) if word[i] in vowels]
			if stress_position>len(vowel_positions):
				continue
			stress_position=vowel_positions[stress_position-1]
			if tokens[-1]=="fix_yo":
				if word[stress_position]==u"е":
					entry=word[:stress_position]+u"ё"+word[stress_position+1:]
				else:
					continue
			elif word[stress_position]==u"ё":
				entry=word
				word=word.replace(u"ё",u"е")
			else:
					entry=word[:stress_position]+word[stress_position].upper()+word[stress_position+1:]
			if word not in lex:
				lex[word]=entry
	with codecs.open("dict","w","utf-8") as f_out:
		for word,entry in sorted(lex.iteritems(),key=lambda p: p[0]):
			f_out.write(entry)
			f_out.write("\n")
