import os.path

Import("env")

for language_path in Glob("languages/*",strings=True):
    env.InstallData(Glob(language_path+"/*"),language_path)
for voice_path in Glob("voices/*",strings=True):
    env.InstallData(Glob(voice_path+"/*"),voice_path)
