# -*- coding: utf-8; mode: Python; indent-tabs-mode: t -*-

import sys
import os
import os.path
import RHVoicePackaging.nvda
import RHVoicePackaging.windows
import RHVoiceInfoParser

Import("env")
local_env=env.Clone()

def list_files(dir):
	files=[]
	for name in sorted(os.listdir(dir.abspath)):
		node_path=os.path.join(dir.abspath,name)
		if os.path.isfile(node_path):
			files.append(dir.File(name))
		elif os.path.isdir(node_path):
			files.extend(list_files(dir.Dir(name)))
	return files

root_dir=Dir(".").srcnode()

lang_msis=dict()

msi_build_number=".1"
exe_build_number=".4"

for dir_name in ["languages","voices"]:
	type=dir_name[:-1]
	dir=root_dir.Dir(dir_name)
	for subdir_name in os.listdir(dir.abspath):
		subdir=dir.Dir(subdir_name)
		data_files=list_files(subdir)
		props=RHVoiceInfoParser.parse(subdir.File(type+".info").abspath)
		if type=="language":
			props["language"]=props["name"]
		if props["language"].lower() not in local_env["languages"]:
			continue
		props["display_language"]=props["language"].replace("-"," ")
		props["type"]=type
		if "file_name" not in props:
			props["file_name"]=props["name"]
		version="{format}.{revision}".format(**props)
		name_format_string="RHVoice-voice-{language}-{file_name}" if type=="voice" else "RHVoice-language-{language}"
		name=name_format_string.format(**props)
		package_name=props.get("package_name",name)
		description_format_string=u"{name} - {display_language} voice for RHVoice" if type=="voice" else "{display_language} language pack for RHVoice"
		description=description_format_string.format(**props)
		if sys.platform!="win32" and not local_env["dev"]:
			for f in data_files:
				local_env.InstallData(f,os.path.relpath(f.Dir(".").abspath,root_dir.abspath))
		packagers=dict()
		if sys.platform=="win32":
			pkgdir=Dir("..").Dir("packages")
			packagers["nvda"]=RHVoicePackaging.nvda.addon_packager(package_name,pkgdir.Dir("nvda"),local_env,package_name,description,description,version,True)
			packagers["msi"]=RHVoicePackaging.windows.data_packager(props["msi_upgrade_code"],package_name,pkgdir.Dir("sapi"),local_env,description,version+msi_build_number)
			for f in data_files:
				packagers["nvda"].add(f,os.path.normpath(os.path.join("data",os.path.relpath(f.Dir(".").abspath,subdir.abspath))))
				packagers["msi"].add(f,os.path.normpath(os.path.join("data",type+"s",props["file_name"],os.path.relpath(f.Dir(".").abspath,subdir.abspath))))
			if type=="language":
				lang_msis[props["name"]]=packagers["msi"]
			else:
				packagers["msi"].visible="no"
				packagers["exe"]=RHVoicePackaging.windows.nsis_bootstrapper_packager(package_name,pkgdir.Dir("sapi"),local_env,description,version+exe_build_number)
				if env["enable_x64"]:
					packagers["exe"].msis.append(local_env["WindowsInstallers_core_64"])
				packagers["exe"].msis.append(local_env["WindowsInstallers_core_32"])
				packagers["exe"].msis.append(lang_msis[props["language"]])
				packagers["exe"].msis.append(packagers["msi"])
		for p in packagers.values():
			p.package()
