#define UDTK_NEWLINE                          1
#define UDTK_EQUALS                           2
#define UDTK_SPACE                            3
#define UDTK_STAR                             4
#define UDTK_COLON                            5
#define UDTK_AND                              6
#define UDTK_LPAREN                           7
#define UDTK_RPAREN                           8
#define UDTK_LBRACE                           9
#define UDTK_RBRACE                          10
#define UDTK_COMMA                           11
#define UDTK_NATIVE_LETTERS                  12
#define UDTK_ENGLISH_LETTERS                 13
#define UDTK_SYM                             14
#define UDTK_PLUS                            15
#define UDTK_STRESSED_SYL_NUMBER             16
#define UDTK_UNSTRESSED                      17
#define UDTK_INITIALISM                      18
#define UDTK_FOREIGN                         19
#define UDTK_NATIVE                          20
#define UDTK_X_SAMPA                         21
