#!/usr/bin/python2
# -*- coding: utf-8; mode: Python; indent-tabs-mode: t; tab-width: 4; python-indent: 4 -*-

# Copyright (C) 2012  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
import os.path
import codecs
import decimal

if __name__=="__main__":
	file_list=sorted(name for name in os.listdir(sys.argv[1]) if name.endswith(".lab"))
	for name in file_list:
		with codecs.open(os.path.join(sys.argv[1],name),"r","utf-8") as f_in:
			with codecs.open(os.path.join(sys.argv[2],name),"w","utf-8") as f_out:
				f_in.readline()
				start=0
				end=0
				for line in f_in:
					fields=line.split()
					if fields:
						phone=fields[-1]
						end=int(decimal.Decimal(fields[0])*10000000)
						f_out.write(u"{} {} {}\n".format(start,end,phone))
						start=end
