#!/usr/bin/python2 -B
# -*- coding: utf-8; mode: Python; indent-tabs-mode: t; tab-width: 4; python-indent: 4 -*-

# Copyright (C) 2012  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import lxml.etree as xml
import sexpr

if __name__=="__main__":
	phoneset=sexpr.read(sys.argv[1])
	spec=phoneset[2]
	entries=phoneset[3]
	root=xml.Element("phonemes")
	for entry in entries:
		elem=xml.Element("phoneme")
		elem.set("name",entry[0])
		for v,s in zip(entry[1:],spec):
			if v!=0:
				elem.set(s[0],str(v))
		root.append(elem)
	xml.ElementTree(root).write(sys.argv[2],pretty_print=True)
