#!/usr/bin/python2
# -*- mode: Python; indent-tabs-mode: t; tab-width: 4; python-indent: 4 -*-

# Copyright (C) 2012  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import argparse
import os
import os.path
import struct
import subprocess
import math

praat_script=os.path.join(os.path.abspath(os.path.dirname(sys.argv[0])),"print-pitch.praat")
rapt_command="sox {f} -t raw -|x2x +sf|pitch -a 0 -o 1 -L {l} -H {h}"

def extract_with_praat(file_name,lower_f0,upper_f0):
	return map(float,subprocess.check_output(["praat",praat_script,file_name,lower_f0,upper_f0,"no"]).split())

def extract_with_rapt(file_name,lower_f0,upper_f0):
	output=subprocess.check_output(rapt_command.format(f=file_name,l=lower_f0,h=upper_f0),shell=True)
	count=len(output)/4
	return struct.unpack("={}f".format(count),output)

def extract_with_tempo(file_name,lower_f0,upper_f0):
	return map(float,subprocess.check_output(["tempo","-nmsg","-lf0",str(lower_f0),"-uf0",str(upper_f0),file_name,"-"]).split())

def extract_f0(file_name,lower_f0,upper_f0):
	values1=extract_with_praat(file_name,lower_f0,upper_f0)
	values2=extract_with_rapt(file_name,lower_f0,upper_f0)
	values3=extract_with_tempo(file_name,lower_f0,upper_f0)
	values=list()
	for candidates in zip(values1,values2,values3):
		values.append(sorted(candidates)[1])
	return values

if __name__=="__main__":
	arg_parser=argparse.ArgumentParser(description="Calculate log-f0 values using praat")
	arg_parser.add_argument("--wave-dir",required=True,help="the path to the recordings")
	arg_parser.add_argument("--out-dir",required=True,help="the output directory")
	arg_parser.add_argument("--lower-f0",required=True,help="lower f0")
	arg_parser.add_argument("--upper-f0",required=True,help="upper f0")
	args=arg_parser.parse_args()
	audio_dir=os.path.abspath(args.wave_dir)
	lf0_dir=os.path.abspath(args.out_dir)
	try:
		os.mkdir(lf0_dir)
	except OSError:
		pass
	for base_name in sorted(os.listdir(audio_dir)):
		print base_name
		full_name=os.path.join(audio_dir,base_name)
		values=extract_f0(full_name,args.lower_f0,args.upper_f0)
		with open(os.path.join(lf0_dir,os.path.splitext(base_name)[0]+".lf0"),"wb") as f:
		 	for f0 in values:
				if f0==0:
					lf0=-10000000000.0
				else:
					lf0=math.log(f0)
				f.write(struct.pack("=f",lf0))
