#!/usr/bin/python2
# -*- coding: utf-8; mode: Python; indent-tabs-mode: t; tab-width: 4; python-indent: 4 -*-

# Copyright (C) 2012  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import codecs
import os.path
import collections
import re

word_regex=re.compile(ur"(?u)\b[^\d\W]+(['-][^\d\W]+)*\b")
tag_regex=re.compile("<[^<]+>")

def update_word_list(word_list,dirname,filenames):
	for filename in filenames:
		path=os.path.join(dirname,filename)
		if os.path.isfile(path):
			with codecs.open(path,"r","utf-8") as f:
				word_list.update(m.group(0).lower() for m in word_regex.finditer(tag_regex.sub(" ",f.read())))

if __name__=="__main__":
	words=collections.Counter()
	os.path.walk(sys.argv[1],update_word_list,words)
	with codecs.open(sys.argv[2],"w","utf-8") as f:
		for w,c in words.most_common():
			f.write(w)
			f.write("\n")
