# -*- mode: Python; indent-tabs-mode: t; tab-width: 4 -*-
# Copyright (C) 2012, 2018, 2019  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

try:
	basestring
except NameError:
	basestring = str

Import("env")

local_env=env.Clone()
local_env["libversion"]="4.0.0"
local_env["liblevel"]=1

libio=local_env.BuildLibrary(local_env["libio"],["io.cpp"])
if env["PLATFORM"]!="win32":
	local_env.InstallLibrary(libio)
Export("libio")
