# Copyright (C) 2021  Olga Yakovleva <olga@rhvoice.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys

Import("env")
if env["enable_pkg"]:
   local_env=env.Clone()
   local_env["liblevel"]=0
   pkg_src=["package_client.cpp", "curl.cpp", "url_builder.cpp"]
   libpkg=local_env.BuildLibrary("pkg",pkg_src)
   Export("libpkg")
