;; These rules are used in most cases
;; when there are no vowels in the word.

(lts.ruleset
 en_consonants
 ()
 (
  ( # [ л ] # = ee ll )
  ( # [ l ] # = ee ll )
  ( [ б ] # = b ee )
  ( [ б ] = b e )
  ( [ в ] # = v ee )
  ( [ в ] = v e )
  ( [ г ] # = g ee )
  ( [ г ] = g e )
  ( [ д ] # = d ee )
  ( [ д ] = d e )
  ( [ ж ] # = zh ee )
  ( [ ж ] = zh e )
  ( [ з ] # = z ee )
  ( [ з ] = z e )
  ( [ й ] = i k r aa t k ay j e )
  ( [ к ] # = k aa )
  ( [ к ] = k a )
  ( [ л ] # = ee l )
  ( [ л ] = e l )
  ( [ м ] # = ee m )
  ( [ м ] = e m )
  ( [ н ] # = ee n )
  ( [ н ] = e n )
  ( [ п ] # = p ee )
  ( [ п ] = p e )
  ( [ р ] # = ee r )
  ( [ р ] = e r )
  ( [ с ] # = ee s )
  ( [ с ] = e s )
  ( [ т ] # = t ee )
  ( [ т ] = t e )
  ( [ ф ] # = ee f )
  ( [ ф ] = e f )
  ( [ х ] # = h aa )
  ( [ х ] = h a )
  ( [ ц ] # = c ee )
  ( [ ц ] = c e )
  ( [ ч ] # = ch ee )
  ( [ ч ] = ch e )
  ( [ ш ] # = sh aa )
  ( [ ш ] = sh a )
  ( [ щ ] # = sch aa )
  ( [ щ ] = sch a )
  ( [ b ] # = bb ii )
  ( [ b ] = bb i )
  ( [ c ] # = ss ii )
  ( [ c ] = ss i )
  ( [ d ] # = dd ii )
  ( [ d ] = dd i )
  ( [ f ] # = ee f )
  ( [ f ] = e f )
  ( [ g ] # = d zh ii )
  ( [ g ] = d zh i )
  ( [ h ] # = ee j ch )
  ( [ h ] = e j ch )
  ( [ j ] # = d zh ee j )
  ( [ j ] = d zh e j )
  ( [ k ] # = kk ee j )
  ( [ k ] = kk e j )
  ( [ l ] # = ee l )
  ( [ l ] = e l )
  ( [ m ] # = ee m )
  ( [ m ] = e m )
  ( [ n ] # = ee n )
  ( [ n ] = e n )
  ( [ p ] # = pp ii )
  ( [ p ] = pp i )
  ( [ q ] # = kk j uu )
  ( [ q ] = kk j u )
  ( [ r ] # = ee r )
  ( [ r ] = e r )
  ( [ s ] # = ee s )
  ( [ s ] = e s )
  ( [ t ] # = tt ii )
  ( [ t ] = tt i )
  ( [ v ] # = vv ii )
  ( [ v ] = vv i )
  ( [ w ] = d aa b l j u )
  ( [ x ] # = ee k s )
  ( [ x ] = e k s )
  ( [ y ] # = v aa j )
  ( [ y ] = v a j )
  ( [ z ] # = z ee d )
  ( [ z ] = z e d )
  ( [ + ] = )
  ( [ - ] = )
  ( [ "'" ] = )
  ))

(provide 'ru_consonants_lts)
