FIND_PATH(LIBPULSESIMPLE_INCLUDE_DIR simple.h /usr/include/pulse /usr/local/include/pulse)
  
FIND_LIBRARY(LIBPULSESIMPLE_LIBRARIES NAMES pulse-simple PATH /usr/lib /usr/local/lib)

IF (LIBPULSESIMPLE_INCLUDE_DIR AND LIBPULSESIMPLE_LIBRARIES)
  SET(LIBPULSESIMPLE_FOUND TRUE)
ENDIF (LIBPULSESIMPLE_INCLUDE_DIR AND LIBPULSESIMPLE_LIBRARIES)

IF (LIBPULSESIMPLE_FOUND)
   IF (NOT LIBPULSESIMPLE_FIND_QUIETLY)
      MESSAGE(STATUS "Found libpublic-simple: ${LIBPULSESIMPLE_LIBRARIES}")
   ENDIF (NOT LIBPULSESIMPLE_FIND_QUIETLY)
ELSE (LIBPULSESIMPLE_FOUND)
   IF (LIBPULSESIMPLE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find libpulse-simple")
   ENDIF (LIBPULSESIMPLE_FIND_REQUIRED)
ENDIF (LIBPULSESIMPLE_FOUND)

