# Copyright (C) 2013, 2014  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Import(["env"])

import RHVoicePackaging.windows

packager=RHVoicePackaging.windows.app_packager("RHVoice",Dir("..").Dir("packages").Dir("sapi"),env,"RHVoice",env["package_version"])
packager.add(Dir("..").Dir("x86").Dir("sapi").File("RHVoiceSvr.dll"),"lib32",regdll=True)
if env["enable_x64"]:
    packager.add(Dir("..").Dir("x86_64").Dir("sapi").File("RHVoiceSvr.dll"),"lib64",regdll=True,x64=True)
packager.add(Dir("..").File("RHVoice.ini"),"config-examples")
packager.add_reg_value("HKLM",r"Software\RHVoice","path","$$INSTDIR")
packager.add_reg_value("HKLM",r"Software\RHVoice","data_path",r'$$INSTDIR\data',True)
packager.add_reg_value("HKLM",r"Software\Microsoft\Speech\Voices\TokenEnums\RHVoice","CLSID","{d7577808-7ade-4dea-a5b7-ee314d6ef3a1}",True)
packager.package()
