/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_olga_yakovleva_rhvoice_LanguageInfo */

#ifndef _Included_com_github_olga_yakovleva_rhvoice_LanguageInfo
#define _Included_com_github_olga_yakovleva_rhvoice_LanguageInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_olga_yakovleva_rhvoice_RHVoiceException */

#ifndef _Included_com_github_olga_yakovleva_rhvoice_RHVoiceException
#define _Included_com_github_olga_yakovleva_rhvoice_RHVoiceException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_olga_yakovleva_rhvoice_RHVoiceException_serialVersionUID
#define com_github_olga_yakovleva_rhvoice_RHVoiceException_serialVersionUID -3042686055658047285LL
#undef com_github_olga_yakovleva_rhvoice_RHVoiceException_serialVersionUID
#define com_github_olga_yakovleva_rhvoice_RHVoiceException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_olga_yakovleva_rhvoice_SynthesisParameters */

#ifndef _Included_com_github_olga_yakovleva_rhvoice_SynthesisParameters
#define _Included_com_github_olga_yakovleva_rhvoice_SynthesisParameters
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_olga_yakovleva_rhvoice_TTSClient */

#ifndef _Included_com_github_olga_yakovleva_rhvoice_TTSClient
#define _Included_com_github_olga_yakovleva_rhvoice_TTSClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_olga_yakovleva_rhvoice_TTSEngine */

#ifndef _Included_com_github_olga_yakovleva_rhvoice_TTSEngine
#define _Included_com_github_olga_yakovleva_rhvoice_TTSEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    onClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_onClassInit
  (JNIEnv *, jclass);

/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    onInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Lcom/github/olga_yakovleva/rhvoice/Logger)V
 */
JNIEXPORT void JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_onInit
(JNIEnv *, jobject, jstring, jstring, jobjectArray, jstring, jobject);

/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    onShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_onShutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    doGetVoices
 * Signature: ()[Lcom/github/olga_yakovleva/rhvoice/VoiceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_doGetVoices
  (JNIEnv *, jobject);

/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    doSpeak
 * Signature: (Ljava/lang/String;Lcom/github/olga_yakovleva/rhvoice/SynthesisParameters;Lcom/github/olga_yakovleva/rhvoice/TTSClient;)V
 */
JNIEXPORT void JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_doSpeak
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     com_github_olga_yakovleva_rhvoice_TTSEngine
 * Method:    doConfigure
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_doConfigure
(JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jstring JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_doGetCachedPackageDir
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_github_olga_1yakovleva_rhvoice_TTSEngine_doGetPackageDirFromServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_olga_yakovleva_rhvoice_VoiceInfo */

#ifndef _Included_com_github_olga_yakovleva_rhvoice_VoiceInfo
#define _Included_com_github_olga_yakovleva_rhvoice_VoiceInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
