# Copyright (C) 2012, 2013  Olga Yakovleva <yakovleva.o.v@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import os.path
import zipfile

Import(["env","data_files"])

def package_addon(env,target,source):
    with zipfile.ZipFile(str(target[0]),"w",zipfile.ZIP_DEFLATED) as f:
        for s,p in zip(source,env["file_paths"]):
            f.write(str(s),p)
    return None

def shorten_path(path,level=1):
    if level==0:
        return path
    components=[part for part in path.split(os.sep) if part]
    return os.sep.join(components[-level:])

addon_sources=list()
file_paths=list()

def add(source,level=1,dir=None):
    short_path=shorten_path(str(source),level)
    long_path=os.path.join(dir,short_path) if dir else short_path
    addon_sources.append(source)
    file_paths.append(long_path)

subst_dict={"@version@":"$package_version"}
manifest=env.Substfile("manifest.ini.in",SUBST_DICT=subst_dict)[0]

synthDriver_dir=os.path.join("synthDrivers","RHVoice")

add(manifest)
add("installTasks.py")
add(os.path.join("locale","ru","manifest.ini"),3)
add(os.path.join(synthDriver_dir,"__init__.py"),3)
add(os.path.join("..","x86","lib","RHVoice.dll"),1,synthDriver_dir)
add(os.path.join("..","COPYING.txt"),1,synthDriver_dir)
add(os.path.join("..","RHVoice.ini"),1,os.path.join(synthDriver_dir,"config"))
for dir,subdirs in data_files.iteritems():
        for subdir,files in subdirs.iteritems():
            for file in files:
                add(file,4,synthDriver_dir)

env.Command("RHVoice_${package_version}.nvda-addon",addon_sources,package_addon,file_paths=file_paths)
